### ISSUE TITLE
Could you add resize to "Run Cat"?

### ISSUE THREAD

**Issue by hoaug-tran** [Kyome22/RunCat_for_windows#111]
Known "Run Cat" and great use of it, thank you for developing such interesting software.

I'm using Window 11 (can't minimize Taskbar - Windows 11's Taskbar is quite large), so when using this software the effect, the size of "Run Cat" is too small, really small. I hope you can add resize to "Run Cat" in the future. Thank you very much.

![image](https://user-images.githubusercontent.com/92006941/189348381-1e96566e-7d4a-432b-b7ba-4c6d98afb4cb.png)

**Comment by Gengar-lab** [comment]
Facing same issue on Windows 11 Taskbar. Is there an option to change the size of cat?

**Comment by Kyome22** [comment]
The implementation of RunCat uses NotifyIcon, but it is fixed at 16 x 16 points, so resizing is not possible.

I tried to make the cat size larger using CSDeskBand in the past (#119), but I stopped because it didn't seem to be guaranteed to work on Windows 11.
