### ISSUE TITLE
I would like to use CSDeskBand to increase the display size of my cat

### ISSUE THREAD

**Issue by Kyome22** [Kyome22/RunCat_for_windows#119]
https://github.com/dsafa/CSDeskBand#usage

The cat is too small to see clearly.

**Comment by Kyome22** [comment]
#93

**Comment by somnisomni** [comment]
This won't work on Windows 11 unless using [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher). Patching system element is NOT very ideal for every users I think.

**Comment by Kyome22** [comment]
[zhongyang219/TrafficMonitor](https://github.com/zhongyang219/TrafficMonitor) allows us to insert custom view into the Task Tray in Windows 11.
