### ISSUE TITLE
Windows Defender detect RunCat as Trojan

### ISSUE THREAD

**Issue by SunatP** [Kyome22/RunCat_for_windows#12]
As my topic describe, the Windows Defender detects RunCat has a malicious code Trojan:Win32/Zpevdo.B

**Comment by Kyome22** [comment]
@SunatP 
I released ver 1.6 and attached a compressed zip file. Could you try to install this? I hope fixed this issue...

**Comment by SunatP** [comment]
Ok for V1.6 it's solved the problem
