### ISSUE TITLE
Couldn't find manifest for 'runcat'.

### ISSUE THREAD

**Issue by Ajoke32** [Kyome22/RunCat_for_windows#124]
Couldn't find manifest for 'runcat'.

**Comment by 399dmitr933** [comment]
![изображение_2023-08-12_105919686](https://github.com/Kyome22/RunCat_for_windows/assets/92231006/5ab9c5be-0376-4f01-b9b9-6bc34813137a)

**Comment by ArtemBay** [comment]
i cant install too

**Comment by ETatskyi** [comment]
same for me

**Comment by Kyome22** [comment]
What is manifest?

**Comment by MuhammadBayiz** [comment]
I Found a Solution, First Run `scoop bucket add extras` Then `scoop install extras/runcat` in PowerShell
https://scoop.sh/#/apps?q=runcat

**Comment by 399dmitr933** [comment]
> I Found a Solution, First Run `scoop bucket add extras` Then `scoop install extras/runcat` in PowerShell https://scoop.sh/#/apps?q=runcat

Thanks! It's work!
![изображение_2023-08-24_224918466](https://github.com/Kyome22/RunCat_for_windows/assets/92231006/d88e568a-5f87-45c1-8c6c-5b2638c3df64)
