### ISSUE TITLE
RunCat for Linux

### ISSUE THREAD

**Issue by chuhha** [Kyome22/RunCat_for_windows#126]
Are there plans to make a RunCat program for operating systems based on the Linux kernel?

**Comment by Kyome22** [comment]
@chuhha 
I don't know if it will work on Linux, but a volunteer has created a GNOME Shell version.
https://github.com/win0err/gnome-runcat

**Comment by Jas0nG** [comment]
Here's what u want 😺  
https://github.com/Jas0nG/RunCat_for_Linux
