### ISSUE TITLE
RuCatのlinux対応

### ISSUE THREAD

**Issue by Honahuku** [Kyome22/RunCat_for_windows#14]
こんにちは。
この愉快なソフトウェアをdebやrpm形式で動作する形に移植する計画はありますか？

**Comment by Kyome22** [comment]
@Honahuku 
こんにちは。
残念ですが、現在Linux向けに移植する計画はありません。
ですが、Linux系の移植ですと、win0err氏がGNOME版のRunCatを公開しているようです。
https://github.com/win0err/gnome-runcat
こちらで使用されている画像などは許可して提供しているものですので、公認のソフトウェアになります。
