### ISSUE TITLE
Runcat 1.7 does not work properly

### ISSUE THREAD

**Issue by matsuda0707** [Kyome22/RunCat_for_windows#15]
After update to 1.7, Runcat does not work properly;

1) No startup even I set "strtup" (no icon in the notification area.

2)The alart " opening system file (.dll) came out.

So I went back to 1.6 now

**Comment by Kyome22** [comment]
@matsuda0707 
Which EXE did you install, RunCat_x64 or RunCat_x64_without_netcore?

**Comment by matsuda0707** [comment]
I think I used RunCat_x64.

**Comment by Kyome22** [comment]
@matsuda0707 
I need more detailed information about the spec of your pc.

**Comment by matsuda0707** [comment]
Thanks.
I re-installed x64 version, and now it works well.
Thanks.
