### ISSUE TITLE
显示占用和实际不一致

### ISSUE THREAD

**Issue by ChaoSection** [Kyome22/RunCat_for_windows#23]
系统：win11 22000.282
版本：1.9
原因：显示CPU占用和实际不一致，显示的占用率和占用CPU最高的程序占用率更一致，不是CPU总占用率
![image](https://user-images.githubusercontent.com/17974143/140891036-b49f517a-96d6-4c19-94b6-03394417cfde.png)

**Comment by gitsang** [comment]
并不是和最高占用一致，我觉得只是windows任务管理器的统计方法和这个不一样而已，你去下其他的监控软件，除了空载和满载，其他情况下基本所有监控显示的负载都是不一致的。
