### ISSUE TITLE
Have u ever got a plan for Chrome plugin

### ISSUE THREAD

**Issue by bladeXue** [Kyome22/RunCat_for_windows#28]
such a interesting project, maybe u can try the version of RUNNING CAT IN CHROME

**Comment by bolshoytoster** [comment]
Hi, I made something that will probably work:
https://github.com/bolshoytoster/RunCat_for_chromium
I'd also be willing to implement #22 and #32 if somebody did the animations.

**Comment by Kyome22** [comment]
@bolshoytoster 
I did try it. It's really nice.
