### ISSUE TITLE
the darkTheme and lightTheme seem like it is inverse

### ISSUE THREAD

**Issue by Flashowing** [Kyome22/RunCat_for_windows#34]

**Comment by jonny7read** [comment]
I believe this refers to the OS theme, so the icon is visible on the taskbar - dark theme taskbar displays light icon, light theme displays dark icon. The default theme uses your system settings, which backs up this theory that the cat should be white for a dark theme taskbar 😄.

**Comment by Flashowing** [comment]
get it
