### ISSUE TITLE
Can the Cat run forever ? 

### ISSUE THREAD

**Issue by Ananya2001-an** [Kyome22/RunCat_for_windows#38]
When I am running the runcat.exe file then the cat does appear but only for a few seconds and then it disappears. Is it supposed to be this way or should it run forever?

**Comment by Kyome22** [comment]
@Ananya2001-an 
I think it is just omitted and you can check it in the list of running tasks.

**Comment by Kyome22** [comment]
![IMG_6545](https://user-images.githubusercontent.com/19896354/142173917-959d7627-1718-4a9a-b3cd-75c534da44b2.jpeg)

**Comment by Ananya2001-an** [comment]
Yup I clicked on the pop up but the cat didn't show up at all 
It was like I had to run the file again and again to see it work 
But thanks for your response. 
The runcat animation is really cute.
