### ISSUE TITLE
`bin/` と `obj/` フォルダをGitの管理外にする

### ISSUE THREAD

**Issue by uhooi** [Kyome22/RunCat_for_windows#4]
日本語で失礼します。

`bin/` と `obj/` フォルダ内に格納されているファイルは、iOSアプリ開発でいうIPAファイルのようなものであり、EXEファイルのサイズなどを考えてもGitの管理外にするのがいいと思います。
特に `obj/` フォルダ内のファイルは中間ファイルなので不要です。 `**/Debug/` フォルダ内のファイルもデバッグ時に生成されるので不要です。

私はEXEファイルをGitHubに上げる一般的な方法を知りませんが、リリースページからEXEファイルがダウンロードできたので、それだけでよさそうです。

**Comment by Kyome22** [comment]
@uhooi さんご指摘ありがとうございます。
必要のなさそうなファイルやディレクトリをgitの管理下から除きました。
確かにリリースページからexeファイルを配布できるのでソースの一部としてリポジトリに上げておかなくてもよさそうですね。

**Comment by uhooi** [comment]
@Kyome22 さっそくのご対応ありがとうございます！
お役に立ててよかったです。

1つだけ、READMEのリンクが変わってなくて404エラーになります、、

**Comment by uhooi** [comment]
あ、すみませんブラウザバッグで戻っていたかもしれません、、ちゃんとリンクが消えていますね:pray:
