### ISSUE TITLE
Theme config resets on reboots

### ISSUE THREAD

**Issue by Taskeren** [Kyome22/RunCat_for_windows#60]
Theme config resets on reboots.

I chose the Dark theme and whenever I reboot my computer, it went back to the Default.

**Comment by wikilike7** [comment]
+1， same issue

Looks like RunCat always ignore my choose and set the default setting to light, but actually Dark is my favorite

**Comment by MatheusOliveira-dev** [comment]
Hey @Taskeren / @wikilike7 

I added a PR #67.

Could you guys take a look when it's accepted, please?

**Comment by Kyome22** [comment]
@MatheusOliveira-dev 
Referring to your PR, I made sure to reload UserSetting right after the app started.
https://github.com/Kyome22/RunCat_for_windows/commit/18da85c2e48dcf730d6e81156ca6ce6366990eb6
