### ISSUE TITLE
在macOS上使用?

### ISSUE THREAD

**Issue by ChenYongJie666** [Kyome22/RunCat_for_windows#61]
how can I use this tool on MacOS?

**Comment by b4imetu** [comment]
https://apps.apple.com/app/runcat/id1429033973

**Comment by Kyome22** [comment]
@ChenYongJie666 
The original version is for macOS and you can get RunCat.app on the AppStore.

**Comment by ChenYongJie666** [comment]
thank you !I found it ,and I have already installed the app.
