### ISSUE TITLE
Auto startup does not save runner config

### ISSUE THREAD

**Issue by PIndividual** [Kyome22/RunCat_for_windows#76]
Every time I have to manually set the runner back to parrot if auto startup is enabled.

**Comment by exat500g** [comment]
点Exit退出就自动保存了

**Comment by br0gio** [comment]
Yeah this is so annoying

**Comment by PIndividual** [comment]
> Yeah this is so annoying

Seems that you have to exit the program and run it again manually in order to save the config.
