### ISSUE TITLE
RegistryKeyがDisposeされない

### ISSUE THREAD

**Issue by geforce-hisa0904** [Kyome22/RunCat_for_windows#8]
GetAppsUseThemeメソッドにてNullReferenceExceptionが発生した場合、RegistryKeyがDisposeされていませんでした。
また、NullReferenceExceptionを用いた条件判断はあまり好ましくないので、変更した方がよいかと思います。

**Comment by Kyome22** [comment]
ネット上で見つけた情報を見様見真似で書いただけなので、例外処理などが甘かったですね。
修正ありがとうございます。
