### ISSUE TITLE
支持 .NET 6

### ISSUE THREAD

**Issue by younger-1** [Kyome22/RunCat_for_windows#86]
dotnet 升级 6.0.101 版本后提示无法使用，需安装 .NET 5

**Comment by Haceau-Zoac** [comment]
![image](https://user-images.githubusercontent.com/61569726/151643353-2bc24ef8-e319-4bd5-b1f1-bb6df4b6ae8c.png)
:(

**Comment by b4imetu** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Official support for<span> </span><a href="https://dotnet.microsoft.com/en-us/download/dotnet" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;">.Net</a><span> </span>5.0 has stopped on May 10th, but I think there are still some (outdated) applications that only support specific versions of .Net</p>

Version | Latest release | Latest release date | End of support
-- | -- | -- | --
.NET 5.0 | 5.0.17 | May 10, 2022 | May 10, 2022


</body>
</html>Official support for [.Net](https://dotnet.microsoft.com/en-us/download/dotnet) 5.0 has stopped on May 10th, but I think there are still some (outdated) applications that only support specific versions of .Net

Version	Latest release	Latest release date	End of support
[.NET 5.0](https://dotnet.microsoft.com/en-us/download/dotnet/5.0)	5.0.17	May 10, 2022	May 10, 2022

**Comment by b4imetu** [comment]
https://github.com/Kyome22/RunCat_for_windows/commit/4cfb0fb42c88707e13716c257c3ee192502531e9
