### ISSUE TITLE
Can make a cat big?

### ISSUE THREAD

**Issue by TianaJ3** [Kyome22/RunCat_for_windows#93]
too small..
![cat](https://user-images.githubusercontent.com/102428210/172695460-2ed16776-87b4-4702-9eb0-63642d286e6c.png)

**Comment by Kyome22** [comment]
@TianaJ3 
I too would like to display the cat on a larger scale. But I'm not very familiar with Windows App.
I know that it may be done by using [CSDeskBand](https://github.com/dsafa/CSDeskBand), but I don't know if it works on the latest Windows OS.

**Comment by cuten222** [comment]
@Kyome22 can this feature is possible to apply in future?

**Comment by Kyome22** [comment]
@cuten222 
I have no plan at this time. I have tried twice before but have given up because of the difficulty.
